---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: demo-Application-1
spec:
 replicas: 2
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: demo-1
 template:
  metadata:
   name: demo-App-Pod-1
   labels:
     app: demo-1	 
  spec: 
    containers:
    - name: demo-App-Container-1
      image: siddharadn/app2
      imagePullPolicy: Always
      ports:
      - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
 name: demo-App-Service
spec:
  type: NodePort
  selector:
   app: demo-1
  ports:
   - port: 80
     targetPort: 2000
     nodePort: 30002
...
